server:
  port: 8989
  servlet:
    context-path: /gbmarket-auth
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./user;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
jwt:
  secret: fgs#$dghdfs%#$234hdfslgdfjb43t34t534og$4352
  lifetime: 300000000




