server:
  port: 8189
  servlet:
    context-path: /gbmarket-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
integrations:
  cart-service:
    url: http://localhost:8190/gbmarket-carts/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000


