server:
  port: 8192
spring:
  cloud:
    config:
      server:
        git:
#          uri: file:///z:/ConfigStorage
          uri: file://Users/alekseyandreev/Documents/ConfigBase
#          search-paths: ${GIT_SEARCH_PATH}
